#ifndef CONFIG_ALGERNON_H
#define CONFIG_ALGERNON_H

#include QMK_KEYBOARD_CONFIG_H

#define ONESHOT_TAP_TOGGLE 2
#define ONESHOT_TIMEOUT 3000

#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE

#undef LEADER_TIMEOUT
#define LEADER_TIMEOUT 1000

#endif
